/**
 * services-data.js \u2014 Service domains content (icon-free).
 * Consumed by js/services.js, which attaches the brand icons by index.
 * Each sub-service: S(name, narration, servicesInclude[], deliverables[], clientBenefits[]).
 */
(function () {
  "use strict";
  function S(name, desc, include, deliverables, benefits) {
    return { name: name, desc: desc, include: include, deliverables: deliverables, benefits: benefits };
  }

  window.SERVICES_DATA = [
    {
      id: "service-01",
      num: "01",
      title: "Strategic Business Advisory & Corporate Growth",
      desc: [
        "Prasad Consulting provides strategic advisory and growth-oriented consulting support to organisations seeking long-term sustainability, enhanced competitiveness, improved operational effectiveness and accelerated business growth.",
        "This consulting domain focuses on helping organisations formulate strategic direction, identify growth opportunities, improve performance, create value, and achieve sustainable competitive advantage through structured planning and informed decision-making."
      ],
      subs: [
        S("Corporate Vision Development",
          "Prasad Consulting assists organisations in creating clear, compelling and actionable corporate visions aligned with future market opportunities, technological developments and organisational aspirations.",
          ["Vision formulation workshops", "Strategic direction studies", "Long-term growth modelling", "Corporate aspiration frameworks", "Leadership alignment exercises", "Organisational purpose definition"],
          ["Corporate Vision Statement", "Strategic Vision Paper", "Growth Direction Blueprint", "Executive Strategic Brief"],
          ["Clear organisational direction", "Better leadership alignment", "Improved decision-making", "Enhanced strategic focus"]),
        S("Strategic Planning & Road Mapping",
          "Prasad Consulting develops structured strategic plans and implementation roadmaps that translate vision into executable actions and measurable outcomes.",
          ["Strategic planning exercises", "SWOT analysis", "Environmental scanning", "Business scenario modelling", "Goal-setting frameworks", "Strategic implementation plans"],
          ["Strategic Plan", "Roadmap Document", "Action Matrix", "KPI Framework"],
          ["Clear implementation path", "Organisational alignment", "Improved resource allocation", "Enhanced execution capability"]),
        S("Growth & Expansion Strategy",
          "Prasad Consulting supports organisations in identifying and evaluating growth opportunities, new markets, geographic expansion possibilities and diversification initiatives.",
          ["Growth opportunity assessment", "Expansion studies", "Market attractiveness analysis", "Diversification evaluation", "Revenue growth modelling", "Business scaling studies"],
          ["Growth Strategy Report", "Expansion Blueprint", "Opportunity Assessment", "Revenue Growth Model"],
          ["Accelerated growth", "Better market penetration", "Increased revenue potential", "Reduced expansion risks"]),
        S("Business Case Development",
          "Prasad Consulting develops detailed business cases for new projects, investments, products, ventures and strategic initiatives.",
          ["Opportunity evaluation", "Cost-benefit analysis", "Financial modelling", "Feasibility studies", "Risk analysis", "Investment justification"],
          ["Business Case Report", "Feasibility Study", "Investment Memorandum", "Decision Support Document"],
          ["Better investment decisions", "Reduced uncertainty", "Improved stakeholder confidence", "Stronger project justification"]),
        S("Market Positioning & Competitive Advantage",
          "Prasad Consulting assists organisations in differentiating themselves within competitive markets and creating sustainable competitive advantages.",
          ["Competitive landscape analysis", "Positioning studies", "Brand differentiation strategies", "Value proposition development", "Competitor benchmarking", "Strategic market recommendations"],
          ["Competitive Analysis Report", "Positioning Framework", "Strategic Market Report", "Brand Enhancement Recommendations"],
          ["Stronger market presence", "Enhanced competitiveness", "Improved customer perception", "Sustainable differentiation"]),
        S("Corporate Performance Enhancement",
          "Prasad Consulting evaluates and improves organisational productivity, efficiency and operational effectiveness.",
          ["Productivity studies", "Operational assessments", "Performance benchmarking", "Efficiency analysis", "KPI development", "Process optimisation"],
          ["Performance Assessment Report", "Productivity Improvement Plan", "KPI Dashboard Framework", "Operational Excellence Roadmap"],
          ["Improved productivity", "Reduced inefficiencies", "Better resource utilisation", "Enhanced profitability"]),
        S("Board-Level Strategic Advisory",
          "Prasad Consulting provides independent strategic advisory support to Boards, CXOs, investors and senior leadership teams.",
          ["Strategic reviews", "Executive advisory sessions", "Governance assessments", "Risk evaluations", "Opportunity assessments", "Independent strategic opinions"],
          ["Board Advisory Notes", "Executive Briefing Papers", "Strategic Recommendations", "Governance Improvement Reports"],
          ["Independent perspective", "Better governance", "Improved strategic decisions", "Enhanced stakeholder confidence"]),
        S("Business Intelligence & Strategic Analysis",
          "Prasad Consulting assists organisations in gathering, analysing and interpreting business intelligence for informed decision-making.",
          ["Market intelligence studies", "Strategic forecasting", "Trend analysis", "Competitive intelligence", "Scenario planning", "Strategic assessments"],
          ["Business Intelligence Reports", "Market Assessment Reports", "Trend Analysis Studies", "Strategic Forecast Documents"],
          ["Better decision support", "Improved market awareness", "Enhanced strategic readiness", "Reduced business uncertainty"])
      ]
    },
    {
      id: "service-02",
      num: "02",
      title: "Growth, Diversification & New Venture Development",
      desc: [
        "Prasad Consulting assists organisations, entrepreneurs, startups, promoters, investors and business houses in identifying growth opportunities, creating new business verticals, launching new ventures, developing innovative products, repositioning existing offerings and building sustainable future-ready enterprises.",
        "This consulting domain combines strategic planning, market intelligence, technology evaluation, AI-enabled business analysis, financial modelling and business architecture development to support long-term growth and value creation."
      ],
      subs: [
        S("Startup Advisory & New Venture Creation",
          "Prasad Consulting supports entrepreneurs, promoters, investors and institutions in conceptualising, evaluating and launching new business ventures across multiple sectors.",
          ["Startup concept evaluation", "Opportunity identification", "Business model development", "Market validation", "Financial planning", "Strategic roadmap preparation", "Investor readiness support"],
          ["Startup Strategy Report", "Business Launch Blueprint", "Market Opportunity Assessment", "Investor Presentation Support"],
          ["Reduced startup risks", "Better market alignment", "Stronger business foundations", "Improved funding readiness"]),
        S("Product Development & Product-Build Strategy",
          "Prasad Consulting assists organisations in conceptualising, planning and developing new products and technology solutions from idea stage to commercial deployment.",
          ["Product concept studies", "Product requirement definition", "Product architecture guidance", "Technology evaluation", "Market-fit assessment", "Product commercialisation planning"],
          ["Product Strategy Report", "Product Development Roadmap", "Product Architecture Concept", "Commercialisation Plan"],
          ["Faster product development", "Better market acceptance", "Reduced development uncertainty", "Enhanced commercial viability"]),
        S("Product Diversification Planning",
          "Prasad Consulting supports organisations in identifying opportunities to expand product portfolios and enter adjacent business segments.",
          ["Diversification studies", "Market opportunity analysis", "Product portfolio assessment", "Strategic expansion planning", "Revenue enhancement modelling", "Risk assessment"],
          ["Diversification Strategy Report", "Market Opportunity Assessment", "Product Portfolio Framework", "Revenue Growth Study"],
          ["Multiple revenue streams", "Reduced business dependence", "Improved market resilience", "Enhanced growth potential"]),
        S("Product Repositioning & Market Realignment",
          "Prasad Consulting assists organisations in revitalising products, repositioning offerings and aligning products with changing market requirements.",
          ["Product repositioning studies", "Customer perception analysis", "Competitive benchmarking", "Market realignment strategies", "Product enhancement recommendations", "Growth acceleration plans"],
          ["Repositioning Strategy Report", "Market Alignment Framework", "Competitive Positioning Analysis", "Product Enhancement Roadmap"],
          ["Improved market relevance", "Better customer engagement", "Increased competitiveness", "Extended product life cycle"]),
        S("Proof-of-Concept (PoC) Development Support",
          "Prasad Consulting assists innovators, startups and enterprises in validating concepts before large-scale investment and deployment.",
          ["Concept validation", "Feasibility evaluation", "Technical assessment", "Commercial viability analysis", "Demonstration planning", "Pilot program design"],
          ["PoC Evaluation Report", "Technical Feasibility Study", "Pilot Demonstration Framework", "Commercial Assessment Report"],
          ["Reduced investment risk", "Improved concept validation", "Better investor confidence", "Faster technology adoption"]),
        S("New Strategic Business Unit (SBU) Creation",
          "Prasad Consulting supports organisations in establishing new business divisions and strategic business units aligned with future growth opportunities.",
          ["SBU opportunity assessment", "Business architecture planning", "Revenue model design", "Resource planning", "Organisational structure definition", "Go-to-market strategy"],
          ["SBU Creation Blueprint", "Strategic Growth Plan", "Business Architecture Report", "Organisational Framework"],
          ["Structured business expansion", "Better governance", "Improved resource utilisation", "Sustainable growth platforms"]),
        S("Entrepreneurship Development Programs",
          "Prasad Consulting assists institutions, incubators, entrepreneurs and startup ecosystems in developing entrepreneurial capabilities.",
          ["Entrepreneurship workshops", "Startup mentoring", "Business planning guidance", "Innovation programs", "Leadership development", "Startup ecosystem creation"],
          ["Entrepreneurship Framework", "Startup Development Roadmap", "Mentorship Programs", "Innovation Support Plans"],
          ["Strong entrepreneurial culture", "Better startup success rates", "Improved innovation capability", "Sustainable ecosystem growth"]),
        S("Indigenous Product Evaluation & Capability Assessment",
          "Prasad Consulting evaluates indigenous products, technologies and solutions to assess technical readiness, commercial viability and future growth potential.",
          ["Technology evaluation", "Capability assessment", "Readiness analysis", "Product benchmarking", "Market-fit studies", "Commercialisation assessment"],
          ["Product Evaluation Report", "Technology Readiness Assessment", "Market-Fit Analysis", "Commercial Viability Study"],
          ["Better product decisions", "Improved investment planning", "Enhanced commercial outcomes", "Reduced development risks"]),
        S("AI-Enabled Business Innovation & Growth Modelling",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to accelerate innovation, improve forecasting and identify strategic growth opportunities.",
          ["AI-enabled market analytics", "AI-assisted growth modelling", "Predictive business intelligence", "Strategic trend forecasting", "Opportunity identification", "Innovation acceleration programs"],
          ["AI Growth Assessment Report", "Predictive Analytics Framework", "Innovation Strategy Blueprint", "AI Opportunity Assessment"],
          ["Improved strategic foresight", "Better growth planning", "Faster innovation cycles", "Data-driven decision making"]),
        S("Emerging Technology Opportunity Assessment",
          "Prasad Consulting assists organisations in evaluating emerging technologies and identifying future business opportunities arising from technological disruptions.",
          ["Technology scouting", "Emerging technology assessments", "Future-market analysis", "Industry disruption studies", "Technology adoption roadmaps", "Strategic technology planning"],
          ["Technology Assessment Report", "Emerging Opportunity Study", "Technology Adoption Roadmap", "Strategic Technology Recommendations"],
          ["Future readiness", "Better technology decisions", "Competitive advantage", "Early-mover positioning"])
      ]
    },
    {
      id: "service-03",
      num: "03",
      title: "Due Diligence, Investments & Corporate Transactions",
      desc: [
        "Prasad Consulting provides strategic, technical, operational and business due diligence services to investors, corporations, startups, promoters, financial institutions, foreign OEMs and industrial entities involved in investment decisions, acquisitions, mergers, joint ventures, strategic partnerships and corporate restructuring initiatives.",
        "This consulting domain combines technical expertise, business analysis, financial evaluation, risk assessment and strategic advisory to support informed decision-making and minimise transaction risks. The objective is to provide clients with an independent, professional and objective assessment of opportunities, risks, capabilities, valuation drivers and long-term sustainability before major business commitments are undertaken."
      ],
      subs: [
        S("Due Diligence Studies",
          "Prasad Consulting conducts comprehensive due diligence studies covering business, technical, operational, organisational, market and strategic dimensions of prospective investments, acquisitions and partnerships.",
          ["Business due diligence", "Technical due diligence", "Operational due diligence", "Organisational capability assessment", "Strategic fit analysis", "Market validation studies"],
          ["Due Diligence Report", "Strategic Assessment Report", "Capability Evaluation Study", "Executive Risk Brief"],
          ["Better investment decisions", "Reduced uncertainty", "Improved transaction confidence", "Enhanced stakeholder assurance"]),
        S("Investment Opportunity Assessment",
          "Prasad Consulting evaluates investment opportunities from strategic, commercial and technical perspectives to determine attractiveness and long-term value creation potential.",
          ["Opportunity assessment", "Market attractiveness evaluation", "Commercial viability analysis", "Growth potential assessment", "Strategic fit studies", "Competitive positioning analysis"],
          ["Investment Opportunity Report", "Market Assessment Study", "Strategic Evaluation Paper", "Investment Recommendation Note"],
          ["Better capital allocation", "Improved investment confidence", "Stronger investment rationale", "Reduced investment risks"]),
        S("Mergers & Acquisitions Advisory",
          "Prasad Consulting supports organisations throughout merger and acquisition processes through structured analysis and strategic advisory.",
          ["Target assessment", "Acquisition feasibility studies", "Strategic fit evaluation", "Integration planning", "Post-merger assessment", "Business synergy analysis"],
          ["M&A Assessment Report", "Strategic Fit Study", "Synergy Evaluation Report", "Integration Roadmap"],
          ["Improved transaction outcomes", "Better integration planning", "Reduced acquisition risks", "Enhanced value realisation"]),
        S("Joint Ventures & Strategic Alliances",
          "Prasad Consulting assists organisations in establishing mutually beneficial joint ventures and strategic partnerships.",
          ["Partner identification", "Strategic alignment studies", "Joint venture frameworks", "Governance structures", "Partnership risk assessment", "Collaboration models"],
          ["JV Framework Document", "Strategic Alliance Blueprint", "Governance Structure Recommendations", "Partnership Evaluation Report"],
          ["Stronger partnerships", "Reduced collaboration risks", "Improved alignment", "Enhanced business opportunities"]),
        S("Consortia Formation & Partnership Structuring",
          "Prasad Consulting assists organisations in forming consortia and collaborative structures for strategic programs, large projects and government opportunities.",
          ["Consortium strategy", "Partner evaluation", "Role allocation frameworks", "Capability mapping", "Collaboration architecture", "Governance planning"],
          ["Consortium Formation Plan", "Collaboration Framework", "Capability Matrix", "Partnership Structure Report"],
          ["Stronger bid capability", "Expanded market reach", "Shared competencies", "Improved project success probability"]),
        S("Amalgamations & Corporate Restructuring",
          "Prasad Consulting supports organisations undergoing structural changes, consolidations and strategic reorganisation.",
          ["Corporate restructuring studies", "Organisational redesign", "Business consolidation analysis", "Governance restructuring", "Transition planning", "Integration support"],
          ["Restructuring Blueprint", "Transition Framework", "Organisational Design Report", "Integration Roadmap"],
          ["Improved efficiency", "Better governance", "Enhanced business focus", "Sustainable growth structures"]),
        S("Investment Memoranda Preparation",
          "Prasad Consulting prepares comprehensive investment memoranda and strategic business documentation for investors, funding agencies and financial institutions.",
          ["Business narrative development", "Market assessment inputs", "Growth projections", "Strategic opportunity articulation", "Financial positioning", "Investor communication support"],
          ["Investment Memorandum", "Executive Summary", "Strategic Business Prospectus", "Investor Briefing Pack"],
          ["Improved investor engagement", "Better presentation of opportunities", "Enhanced funding readiness", "Stronger investment propositions"]),
        S("Financial Modelling & Business Evaluation",
          "Prasad Consulting develops strategic financial models and business evaluation frameworks supporting investment and growth decisions.",
          ["Revenue modelling", "Scenario analysis", "Profitability assessment", "Cost-benefit evaluation", "Business valuation support", "Long-term forecasting"],
          ["Financial Model", "Business Evaluation Report", "Revenue Projection Framework", "Financial Forecast Study"],
          ["Better planning", "Improved valuation understanding", "Enhanced decision support", "Stronger investment confidence"]),
        S("Risk Analysis & Sensitivity Studies",
          "Prasad Consulting evaluates risks associated with business opportunities, investments, partnerships and strategic initiatives.",
          ["Risk identification", "Sensitivity analysis", "Scenario modelling", "Strategic risk assessment", "Opportunity-risk balancing", "Mitigation planning"],
          ["Risk Assessment Report", "Sensitivity Analysis Study", "Strategic Risk Matrix", "Risk Mitigation Framework"],
          ["Improved preparedness", "Reduced uncertainty", "Better risk visibility", "Stronger decision-making"]),
        S("Technology, IP & Asset Due Diligence",
          "Prasad Consulting evaluates technology assets, intellectual property, industrial capabilities and specialised infrastructure associated with strategic transactions.",
          ["Technology assessments", "IP evaluations", "Capability reviews", "Industrial asset studies", "Manufacturing readiness assessments", "Technology transfer evaluations"],
          ["Technology Due Diligence Report", "IP Assessment Study", "Asset Evaluation Report", "Technology Readiness Assessment"],
          ["Better technology decisions", "Improved acquisition confidence", "Reduced technical risks", "Enhanced value realisation"]),
        S("AI-Enabled Investment Intelligence & Decision Support",
          "Prasad Consulting leverages AI-assisted analytical methodologies to improve investment evaluations and strategic decision-making.",
          ["Predictive investment analytics", "AI-enabled market intelligence", "Opportunity forecasting", "Strategic trend analysis", "Data-driven decision support", "Risk prediction modelling"],
          ["AI Investment Assessment", "Predictive Intelligence Report", "Opportunity Forecast Framework", "Strategic Decision Dashboard"],
          ["Faster decision support", "Improved analytical depth", "Better forecasting capability", "Enhanced strategic insight"]),
        S("Investor Representation & Strategic Advisory",
          "Prasad Consulting acts as a strategic adviser and representative to investors, promoters and corporate leadership during critical business evaluations and transactions.",
          ["Independent advisory support", "Strategic reviews", "Transaction support", "Executive representation", "Stakeholder engagement", "Negotiation support"],
          ["Strategic Advisory Notes", "Executive Briefing Papers", "Investor Representation Reports", "Negotiation Support Documents"],
          ["Independent expert advice", "Stronger negotiation position", "Improved transaction confidence", "Enhanced strategic outcomes"])
      ]
    },
    {
      id: "service-04",
      num: "04",
      title: "Defence, Aerospace & Homeland Security Consulting",
      desc: [
        "Prasad Consulting provides specialised strategic consulting, technical advisory, business development support and programme guidance in Defence, Aerospace, Homeland Security, Maritime Security, Border Security, Strategic Technologies and National Security domains.",
        "The consulting support is founded upon decades of professional experience in defence services, defence industrial ecosystems, indigenous defence programmes, aerospace technologies, homeland security architectures, military operational systems, strategic infrastructure planning and national capability development.",
        "The objective is to assist governments, armed forces, defence manufacturers, aerospace organisations, homeland security agencies, startups, investors and international OEMs in developing, acquiring, manufacturing, integrating and deploying advanced defence and security capabilities."
      ],
      subs: [
        S("Defence Market Entry & Growth Strategy",
          "Prasad Consulting assists domestic and international organisations seeking entry into defence, aerospace and homeland security sectors.",
          ["Market opportunity assessment", "Defence sector analysis", "Competitor mapping", "Procurement ecosystem studies", "Customer identification", "Growth strategy formulation"],
          ["Defence Market Assessment Report", "Market Entry Blueprint", "Strategic Growth Roadmap", "Customer Opportunity Matrix"],
          ["Faster market penetration", "Better strategic positioning", "Reduced entry risks", "Improved business visibility"]),
        S("Defence Procurement & Acquisition Advisory",
          "Prasad Consulting assists organisations in understanding and responding to defence procurement opportunities.",
          ["Procurement process guidance", "RFI analysis", "RFP analysis", "Bid strategy development", "Technical compliance assessment", "Tender support"],
          ["Procurement Advisory Report", "Tender Strategy Framework", "Compliance Matrix", "Bid Assessment Report"],
          ["Better bid quality", "Improved compliance", "Higher competitiveness", "Reduced proposal risks"]),
        S("Defence Manufacturing & Industrial Capability Development",
          "Prasad Consulting supports defence manufacturers in capability creation, industrial readiness and production enhancement.",
          ["Defence manufacturing studies", "Capability assessments", "Industrial readiness evaluations", "Production ecosystem planning", "Vendor development", "Manufacturing strategy"],
          ["Capability Assessment Report", "Manufacturing Readiness Framework", "Industrial Development Roadmap", "Production Strategy Study"],
          ["Stronger industrial capability", "Better production readiness", "Improved competitiveness", "Sustainable growth"]),
        S("Defence Export Promotion & International Business Development",
          "Prasad Consulting assists organisations in developing export opportunities and expanding into international defence markets.",
          ["Export readiness studies", "International market assessments", "Export strategy development", "Country opportunity analysis", "Business development support", "International partnership facilitation"],
          ["Export Strategy Report", "International Opportunity Matrix", "Market Assessment Study", "Export Growth Roadmap"],
          ["Expanded market reach", "Increased export potential", "Enhanced international visibility", "Improved business opportunities"]),
        S("Defence Product Development & Indigenous Capability Building",
          "Prasad Consulting supports organisations in developing indigenous products and technologies for defence applications.",
          ["Product concept development", "Technology assessment", "Indigenous capability studies", "Product roadmapping", "Technology commercialisation", "Strategic planning support"],
          ["Product Development Roadmap", "Indigenous Capability Study", "Technology Assessment Report", "Commercialisation Framework"],
          ["Stronger indigenous capabilities", "Reduced dependence on imports", "Improved competitiveness", "Enhanced innovation"]),
        S("Aerospace Systems & Technology Consulting",
          "Prasad Consulting provides advisory support across aerospace systems, aerospace technologies and aviation-related opportunities.",
          ["Aerospace technology assessments", "Aerospace industrial studies", "Aerospace programme reviews", "Capability evaluations", "Aviation infrastructure studies", "Aerospace market analysis"],
          ["Aerospace Assessment Report", "Capability Evaluation Study", "Aerospace Market Report", "Strategic Recommendations"],
          ["Better aerospace planning", "Improved technology understanding", "Enhanced business opportunities", "Stronger programme outcomes"]),
        S("Homeland Security & National Security Solutions",
          "Prasad Consulting assists organisations and agencies in planning and implementing homeland security architectures.",
          ["Security architecture studies", "Critical infrastructure protection", "Urban security planning", "Public safety solutions", "National security assessments", "Security integration studies"],
          ["Homeland Security Assessment", "Security Architecture Framework", "Infrastructure Protection Study", "Strategic Security Recommendations"],
          ["Improved security readiness", "Better risk management", "Enhanced situational awareness", "Stronger resilience"]),
        S("Maritime Security & Naval Systems Consulting",
          "Prasad Consulting provides strategic and technical advisory support relating to maritime security, naval technologies and naval capability enhancement.",
          ["Maritime security studies", "Naval systems assessments", "Coastal surveillance planning", "Port security evaluations", "Maritime domain awareness frameworks", "Naval capability reviews"],
          ["Maritime Security Report", "Naval Systems Assessment", "Coastal Security Framework", "Maritime Surveillance Roadmap"],
          ["Improved maritime security", "Better naval preparedness", "Enhanced coastal awareness", "Stronger operational capability"]),
        S("Shipbuilding Infrastructure & Shipyard Development Planning",
          "Prasad Consulting assists governments, naval organisations, shipyards and industrial entities in planning, evaluating and developing shipbuilding infrastructure and maritime industrial ecosystems.",
          ["Shipyard master planning", "Shipbuilding infrastructure assessments", "Maritime industrial ecosystem development", "Naval dockyard planning", "Production facility evaluations", "Capacity expansion studies", "Strategic shipyard growth planning", "Industrial cluster development"],
          ["Shipyard Development Master Plan", "Infrastructure Assessment Report", "Capacity Expansion Blueprint", "Maritime Industrial Development Framework", "Strategic Growth Roadmap"],
          ["Improved infrastructure planning", "Enhanced shipbuilding capability", "Better industrial readiness", "Sustainable maritime growth"]),
        S("Border Security & Integrated Surveillance Solutions",
          "Prasad Consulting supports organisations involved in border security and integrated surveillance systems.",
          ["Border security studies", "Surveillance architecture design", "Sensor integration concepts", "Multi-layer security planning", "Operational effectiveness reviews", "Technology assessments"],
          ["Border Security Framework", "Integrated Surveillance Plan", "Technology Assessment Report", "Capability Enhancement Roadmap"],
          ["Better situational awareness", "Improved border monitoring", "Reduced vulnerabilities", "Enhanced operational effectiveness"]),
        S("Strategic Defence Partnerships & International Collaborations",
          "Prasad Consulting facilitates strategic collaborations among domestic and international organisations.",
          ["Partner identification", "Collaboration studies", "Strategic alignment assessments", "Partnership structuring", "Capability mapping", "Cooperation frameworks"],
          ["Partnership Blueprint", "Strategic Alignment Study", "Collaboration Framework", "Opportunity Assessment"],
          ["Stronger partnerships", "Expanded opportunities", "Improved technology access", "Enhanced business growth"]),
        S("Defence Business Campaigns & Opportunity Pursuit",
          "Prasad Consulting assists organisations in pursuing strategic defence opportunities and programmes.",
          ["Opportunity tracking", "Customer engagement support", "Demonstration planning", "Campaign strategies", "Bid support", "Strategic communication support"],
          ["Campaign Strategy Document", "Opportunity Assessment", "Pursuit Plan", "Executive Briefing Notes"],
          ["Better opportunity conversion", "Improved customer engagement", "Enhanced visibility", "Stronger business outcomes"]),
        S("Defence Technology Assessment & Capability Studies",
          "Prasad Consulting evaluates technologies, capabilities and strategic programmes.",
          ["Technology reviews", "Capability assessments", "Comparative evaluations", "Technology roadmapping", "Programme studies", "Strategic reviews"],
          ["Technology Assessment Report", "Capability Evaluation Study", "Strategic Technology Roadmap", "Programme Review Report"],
          ["Better technology decisions", "Improved capability planning", "Enhanced programme effectiveness", "Reduced technical uncertainty"]),
        S("AI-Enabled Defence & Security Solutions",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence for defence, homeland security, surveillance and military applications.",
          ["AI-enabled surveillance architectures", "AI-assisted decision-support systems", "AI-enabled command-and-control concepts", "Autonomous systems evaluations", "AI-driven intelligence analytics", "Predictive threat assessment", "AI-enabled security operations", "AI-enabled situational awareness frameworks"],
          ["AI Defence Transformation Roadmap", "AI Opportunity Assessment", "Defence AI Strategy Report", "AI Security Architecture Framework", "AI Integration Blueprint"],
          ["Enhanced decision superiority", "Faster operational response", "Improved intelligence generation", "Better resource utilisation", "Future-ready defence capabilities"])
      ]
    },
    {
      id: "service-05",
      num: "05",
      title: "Surveillance, Security & Cyber Defence Solutions",
      desc: [
        "Prasad Consulting provides comprehensive consulting, advisory, assessment, planning, architecture development, implementation guidance and technology support services in the fields of surveillance, physical security, cyber security, information security, perimeter protection, integrated security management and security operations.",
        "The consulting services cover corporate, industrial, critical infrastructure, defence, aerospace, maritime, homeland security, logistics, transportation, educational, energy and government sectors.",
        "The objective is to create secure, resilient, technology-enabled and future-ready environments capable of protecting people, assets, information, operations and critical infrastructure against evolving threats and vulnerabilities."
      ],
      subs: [
        S("Security Risk Assessment & Security Audits",
          "Prasad Consulting conducts comprehensive security audits and risk assessments to identify weaknesses, security gaps and areas requiring enhancement.",
          ["Security audits", "Security inspections", "Site surveys", "Risk identification", "Compliance assessments", "Security benchmarking"],
          ["Security Audit Report", "Risk Assessment Report", "Security Compliance Matrix", "Recommendations Framework"],
          ["Improved visibility of risks", "Better compliance", "Stronger security posture", "Reduced vulnerabilities"]),
        S("Threat & Vulnerability Analysis",
          "Prasad Consulting evaluates existing and emerging threats that may impact organisational operations, infrastructure and personnel.",
          ["Threat analysis", "Vulnerability mapping", "Risk prioritisation", "Attack-path assessments", "Exposure analysis", "Security gap identification"],
          ["Threat Assessment Report", "Vulnerability Analysis Report", "Security Gap Matrix", "Risk Prioritisation Framework"],
          ["Better threat awareness", "Improved preparedness", "Reduced exposure", "Enhanced resilience"]),
        S("Surveillance System Studies & Security Architecture Design",
          "Prasad Consulting assists organisations in planning surveillance systems and designing integrated security architectures.",
          ["CCTV architecture studies", "Sensor deployment planning", "Camera coverage studies", "Technology assessments", "System integration concepts", "Surveillance optimisation"],
          ["Surveillance Design Report", "Coverage Analysis", "Security Architecture Blueprint", "Technology Recommendation Report"],
          ["Better surveillance coverage", "Improved operational effectiveness", "Reduced blind spots", "Enhanced situational awareness"]),
        S("Integrated Surveillance & Security Master Planning",
          "Prasad Consulting develops long-term integrated surveillance and security master plans for industrial facilities, campuses, critical infrastructure and strategic establishments.",
          ["Security master planning", "Multi-layer security concepts", "Long-term capability planning", "Technology integration studies", "Future expansion planning", "Security roadmap development"],
          ["Security Master Plan", "Integrated Security Blueprint", "Strategic Security Roadmap", "Expansion Planning Framework"],
          ["Structured long-term planning", "Better investment utilisation", "Improved security effectiveness", "Future-ready infrastructure"]),
        S("Perimeter Security & Border Security Solutions",
          "Prasad Consulting assists organisations in securing large perimeters, strategic boundaries and sensitive facilities.",
          ["Perimeter security studies", "Border surveillance concepts", "Fence and barrier assessments", "Sensor integration planning", "Detection architecture development", "Intrusion management concepts"],
          ["Perimeter Security Plan", "Border Security Framework", "Intrusion Detection Architecture", "Security Enhancement Roadmap"],
          ["Improved perimeter protection", "Early threat detection", "Reduced intrusion risks", "Enhanced security control"]),
        S("Physical Security Enhancement Programmes",
          "Prasad Consulting assists organisations in strengthening physical security arrangements and operational readiness.",
          ["Access control studies", "Security deployment reviews", "Guard force evaluations", "Security process assessments", "Visitor management studies", "Security improvement programmes"],
          ["Physical Security Assessment", "Access Control Framework", "Security Enhancement Plan", "Operational Recommendations"],
          ["Improved facility security", "Better access management", "Enhanced operational control", "Reduced security incidents"]),
        S("Information Security Consulting",
          "Prasad Consulting assists organisations in protecting information assets, sensitive data and business-critical systems.",
          ["Information security assessments", "Security policy development", "Data protection strategies", "Governance frameworks", "Information risk management", "Compliance support"],
          ["Information Security Framework", "Security Policy Suite", "Data Protection Strategy", "Governance Recommendations"],
          ["Improved data security", "Better governance", "Enhanced compliance", "Reduced information risks"]),
        S("Cyber Security Assessment & Hardening",
          "Prasad Consulting assists organisations in strengthening cyber resilience through systematic assessments and hardening initiatives.",
          ["Cyber security audits", "Security posture reviews", "Vulnerability assessments", "Hardening recommendations", "Network security reviews", "Penetration modelling"],
          ["Cyber Security Assessment Report", "Hardening Framework", "Vulnerability Assessment Report", "Security Improvement Plan"],
          ["Improved cyber resilience", "Reduced cyber exposure", "Better security controls", "Enhanced confidence"]),
        S("Cyber Defence Strategy & Security Operations",
          "Prasad Consulting supports organisations in developing cyber defence capabilities and security operations frameworks.",
          ["Cyber defence planning", "Security operations concepts", "Incident response planning", "Threat intelligence integration", "Monitoring strategies", "Cyber resilience frameworks"],
          ["Cyber Defence Strategy", "Security Operations Framework", "Incident Response Plan", "Cyber Resilience Roadmap"],
          ["Improved response capability", "Enhanced threat detection", "Better operational readiness", "Stronger cyber posture"]),
        S("Security Dashboard, MIS & Command Centre Solutions",
          "Prasad Consulting assists organisations in developing integrated command centres, monitoring centres and executive dashboards.",
          ["Command centre architecture", "MIS design", "Dashboard development concepts", "Security monitoring frameworks", "Data integration studies", "Operational visualisation concepts"],
          ["Command Centre Blueprint", "Dashboard Architecture", "MIS Framework", "Operational Monitoring Design"],
          ["Centralised monitoring", "Better decision support", "Improved visibility", "Enhanced operational control"]),
        S("AI-Enabled Surveillance & Intelligent Monitoring Systems",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to transform surveillance and security operations.",
          ["AI-enabled video analytics", "Intelligent object detection", "Behavioural analytics", "AI-assisted threat detection", "Smart monitoring architectures", "Predictive security analytics", "Autonomous surveillance concepts", "Intelligent command-and-control integration"],
          ["AI Surveillance Strategy", "Intelligent Monitoring Framework", "AI Analytics Assessment", "Smart Security Architecture", "AI Integration Roadmap"],
          ["Enhanced detection capability", "Reduced false alarms", "Faster threat identification", "Improved operational efficiency", "Future-ready surveillance capability"]),
        S("Security Training, Awareness & Preparedness Programmes",
          "Prasad Consulting conducts awareness programmes, training initiatives and preparedness exercises.",
          ["Security awareness training", "Security drills", "Preparedness assessments", "Incident response exercises", "Cyber awareness programmes", "Executive security workshops"],
          ["Training Framework", "Awareness Programme Plan", "Preparedness Assessment", "Security Exercise Report"],
          ["Improved readiness", "Better awareness", "Enhanced response capability", "Stronger security culture"]),
        S("Critical Infrastructure Protection Solutions",
          "Prasad Consulting assists critical infrastructure operators in protecting essential facilities and strategic assets.",
          ["Infrastructure protection studies", "Risk assessments", "Security architecture reviews", "Continuity planning", "Resilience assessments", "Threat mitigation planning"],
          ["Infrastructure Protection Framework", "Risk Assessment Report", "Resilience Roadmap", "Strategic Recommendations"],
          ["Improved resilience", "Better risk management", "Enhanced protection", "Reduced operational disruptions"]),
        S("Security Technology Evaluation & Selection",
          "Prasad Consulting assists organisations in evaluating and selecting security technologies and solution providers.",
          ["Technology assessments", "Vendor evaluations", "Comparative studies", "Capability reviews", "Technical benchmarking", "Procurement support"],
          ["Technology Evaluation Report", "Vendor Assessment Matrix", "Comparative Analysis Report", "Procurement Recommendations"],
          ["Better technology choices", "Reduced procurement risks", "Improved value realisation", "Stronger investment decisions"])
      ]
    },
    {
      id: "service-06",
      num: "06",
      title: "Quality Systems, Certifications & Regulatory Facilitation",
      desc: [
        "Prasad Consulting provides comprehensive advisory, implementation support, facilitation, readiness assessment and strategic guidance services relating to quality management systems, industry certifications, regulatory compliance frameworks, accreditation programmes, government approvals and institutional excellence initiatives.",
        "The objective is to assist organisations in establishing robust management systems, improving operational quality, achieving regulatory compliance, enhancing organisational credibility and securing nationally and internationally recognised certifications.",
        "The consulting support covers industrial organisations, manufacturing enterprises, defence industries, aerospace organisations, technology firms, educational institutions, startups and service-sector entities."
      ],
      subs: [
        S("Quality Management System (QMS) Implementation",
          "Prasad Consulting assists organisations in establishing, strengthening and institutionalising quality management systems aligned with international standards and best practices.",
          ["QMS gap assessments", "Process documentation", "Quality framework development", "Internal readiness reviews", "Process standardisation", "Implementation guidance"],
          ["QMS Framework", "Process Documentation Package", "Quality Manual", "Implementation Roadmap"],
          ["Improved operational consistency", "Better process control", "Enhanced customer confidence", "Improved quality performance"]),
        S("ISO Certification Readiness & Facilitation",
          "Prasad Consulting supports organisations in achieving certification readiness for various ISO standards (ISO 9001, ISO 22001, ISO 22031, ISO 27001, ISO 27031, ISO 27032 and other applicable standards).",
          ["Gap analysis", "Documentation support", "Readiness assessments", "Internal audit guidance", "Corrective action planning", "Certification preparedness"],
          ["Gap Assessment Report", "Certification Readiness Framework", "Documentation Package", "Audit Preparation Checklist"],
          ["Faster certification readiness", "Improved compliance", "Better process maturity", "Enhanced credibility"]),
        S("Aerospace & Defence Quality Standards Support",
          "Prasad Consulting assists aerospace and defence organisations in implementing specialised quality standards and compliance frameworks.",
          ["AS9100 readiness", "Defence quality systems", "Aerospace compliance studies", "Process control frameworks", "Configuration management guidance", "Quality assurance reviews"],
          ["Aerospace Quality Framework", "Compliance Assessment", "Quality Assurance Roadmap", "Readiness Evaluation Report"],
          ["Enhanced industry credibility", "Improved compliance", "Better programme readiness", "Increased business opportunities"]),
        S("Capability Maturity & Process Excellence Programmes",
          "Prasad Consulting supports organisations in improving process maturity and operational excellence.",
          ["Process maturity assessments", "CMMI readiness guidance", "Capability improvement planning", "Process optimisation", "Performance reviews", "Continuous improvement programmes"],
          ["Capability Assessment Report", "Process Improvement Framework", "Excellence Roadmap", "Maturity Enhancement Plan"],
          ["Improved organisational capability", "Better operational efficiency", "Enhanced competitiveness", "Sustainable improvement"]),
        S("Regulatory Compliance & Governance Support",
          "Prasad Consulting assists organisations in understanding and complying with applicable regulations, standards and governance requirements.",
          ["Compliance assessments", "Governance reviews", "Regulatory mapping", "Policy development", "Risk identification", "Compliance monitoring frameworks"],
          ["Compliance Assessment Report", "Governance Framework", "Regulatory Compliance Matrix", "Policy Recommendations"],
          ["Reduced compliance risks", "Improved governance", "Better organisational control", "Enhanced stakeholder confidence"]),
        S("DGQA Facilitation & Defence Quality Assurance Support",
          "Prasad Consulting assists defence manufacturers in understanding and preparing for DGQA-related requirements and quality assurance frameworks.",
          ["Readiness assessments", "Quality documentation support", "Process evaluations", "Compliance guidance", "Defence quality reviews", "Quality assurance planning"],
          ["DGQA Readiness Report", "Quality Documentation Package", "Compliance Framework", "Improvement Recommendations"],
          ["Better preparedness", "Improved quality assurance", "Enhanced defence business readiness", "Stronger compliance posture"]),
        S("CEMILAC Facilitation & Aerospace Certification Support",
          "Prasad Consulting supports aerospace and aviation organisations in preparing for certification and airworthiness-related processes.",
          ["Certification readiness assessments", "Documentation reviews", "Compliance planning", "Process guidance", "Quality assurance support", "Programme reviews"],
          ["Certification Readiness Assessment", "Compliance Framework", "Documentation Support Package", "Improvement Roadmap"],
          ["Improved certification readiness", "Enhanced compliance", "Better programme assurance", "Increased credibility"]),
        S("DSIR, CSIR & SERB Recognition Support",
          "Prasad Consulting assists organisations in obtaining research, innovation and scientific recognition from relevant agencies.",
          ["Eligibility assessments", "Documentation support", "Application guidance", "Research capability reviews", "Innovation framework assessments", "Recognition preparedness"],
          ["Recognition Readiness Report", "Application Support Documentation", "Capability Assessment", "Strategic Recommendations"],
          ["Enhanced institutional recognition", "Improved research visibility", "Greater funding opportunities", "Stronger innovation ecosystem"]),
        S("Government Grants, Incentives & Funding Facilitation",
          "Prasad Consulting assists organisations in identifying and pursuing grants, incentives and funding opportunities.",
          ["Opportunity identification", "Eligibility assessments", "Proposal support", "Documentation preparation", "Strategic guidance", "Funding readiness reviews"],
          ["Funding Opportunity Matrix", "Grant Support Package", "Proposal Framework", "Funding Readiness Assessment"],
          ["Better access to funding", "Improved proposal quality", "Enhanced project viability", "Reduced funding uncertainty"]),
        S("DRDO, Defence Innovation & Research Support",
          "Prasad Consulting assists organisations in engaging with defence innovation programmes and research ecosystems.",
          ["Defence innovation guidance", "Research programme support", "Technology opportunity assessments", "Proposal reviews", "Strategic advisory", "Innovation ecosystem engagement"],
          ["Innovation Opportunity Report", "Research Engagement Framework", "Strategic Recommendations", "Programme Participation Roadmap"],
          ["Improved innovation participation", "Better programme understanding", "Enhanced growth opportunities", "Stronger technology positioning"]),
        S("Industrial Licensing & Regulatory Approvals",
          "Prasad Consulting assists organisations in navigating licensing and regulatory approval requirements.",
          ["Licensing assessments", "Documentation guidance", "Regulatory mapping", "Approval support", "Strategic compliance reviews", "Process facilitation"],
          ["Licensing Readiness Report", "Regulatory Compliance Framework", "Approval Roadmap", "Documentation Support Package"],
          ["Faster approval readiness", "Reduced compliance risks", "Improved regulatory understanding", "Better business preparedness"]),
        S("IPO, Investment & Institutional Compliance Support",
          "Prasad Consulting supports organisations preparing for institutional investment, expansion and public market participation.",
          ["Compliance reviews", "Documentation assessments", "Governance readiness studies", "Strategic advisory", "Institutional preparedness reviews", "Investor-facing documentation support"],
          ["Compliance Assessment", "Governance Readiness Framework", "Strategic Advisory Report", "Institutional Readiness Study"],
          ["Improved investor confidence", "Better governance", "Enhanced organisational maturity", "Stronger growth readiness"]),
        S("AI-Enabled Quality Management & Compliance Analytics",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to strengthen quality systems, audits, compliance monitoring and process excellence.",
          ["AI-assisted compliance monitoring", "Predictive quality analytics", "Intelligent audit support", "Process performance analytics", "AI-enabled risk identification", "Compliance intelligence frameworks"],
          ["AI Quality Assessment Report", "Compliance Analytics Framework", "Predictive Quality Dashboard", "AI Transformation Roadmap"],
          ["Faster compliance monitoring", "Improved audit readiness", "Better process visibility", "Enhanced decision-making", "Future-ready quality systems"]),
        S("Organisational Excellence & Continuous Improvement Programmes",
          "Prasad Consulting assists organisations in institutionalising excellence, continuous improvement and performance enhancement cultures.",
          ["Excellence assessments", "Improvement initiatives", "Benchmarking studies", "Organisational reviews", "Process enhancement programmes", "Long-term improvement planning"],
          ["Excellence Framework", "Improvement Roadmap", "Benchmarking Report", "Strategic Recommendations"],
          ["Improved organisational performance", "Enhanced competitiveness", "Stronger quality culture", "Sustainable growth"])
      ]
    },
    {
      id: "service-07",
      num: "07",
      title: "Corporate Transformation & Organisational Excellence",
      desc: [
        "Prasad Consulting assists organisations in transforming themselves into agile, efficient, competitive and future-ready enterprises through structured organisational change, business process improvement, governance enhancement, leadership development and strategic transformation initiatives.",
        "The objective is to support organisations in adapting to evolving business environments, emerging technologies, changing customer expectations, competitive pressures and growth aspirations while maintaining operational excellence and long-term sustainability.",
        "This consulting domain combines strategic thinking, organisational development, business process reengineering, AI-enabled transformation methodologies and executive leadership engagement to deliver measurable business outcomes."
      ],
      subs: [
        S("Organisational Transformation & Change Management",
          "Prasad Consulting assists organisations in successfully managing transformational initiatives, structural changes and business evolution programmes.",
          ["Change readiness assessments", "Transformation strategy development", "Stakeholder engagement", "Communication frameworks", "Organisational transition planning", "Change adoption support"],
          ["Transformation Blueprint", "Change Management Framework", "Stakeholder Engagement Plan", "Transformation Roadmap"],
          ["Smoother transitions", "Reduced organisational resistance", "Improved adoption rates", "Enhanced transformation success"]),
        S("Business Process Reengineering (BPR)",
          "Prasad Consulting assists organisations in redesigning and optimising business processes to improve efficiency, agility and effectiveness.",
          ["Process mapping", "Process diagnostics", "Bottleneck identification", "Workflow redesign", "Process simplification", "Best-practice integration"],
          ["Process Reengineering Report", "Workflow Redesign Framework", "Process Improvement Roadmap", "Efficiency Enhancement Plan"],
          ["Faster operations", "Reduced process inefficiencies", "Improved service delivery", "Enhanced productivity"]),
        S("Operational Effectiveness Enhancement",
          "Prasad Consulting assists organisations in improving operational performance and achieving superior business outcomes.",
          ["Operational assessments", "Resource utilisation studies", "Efficiency reviews", "Process optimisation", "Operational benchmarking", "Performance diagnostics"],
          ["Operational Effectiveness Report", "Improvement Recommendations", "Performance Enhancement Framework", "Operational Excellence Roadmap"],
          ["Better operational control", "Improved efficiency", "Reduced waste", "Higher business performance"]),
        S("Productivity Improvement & Performance Optimisation",
          "Prasad Consulting assists organisations in enhancing productivity across departments, facilities and business functions.",
          ["Productivity assessments", "Performance evaluations", "Benchmarking studies", "KPI development", "Performance improvement initiatives", "Continuous monitoring frameworks"],
          ["Productivity Assessment Report", "KPI Framework", "Performance Improvement Plan", "Benchmarking Study"],
          ["Increased productivity", "Better resource utilisation", "Improved profitability", "Enhanced organisational performance"]),
        S("Corporate Governance & Management Systems",
          "Prasad Consulting assists organisations in strengthening governance structures and management systems.",
          ["Governance assessments", "Policy reviews", "Organisational control frameworks", "Accountability structures", "Risk governance reviews", "Management system enhancement"],
          ["Governance Framework", "Management System Assessment", "Policy Recommendations", "Governance Improvement Roadmap"],
          ["Better organisational control", "Enhanced accountability", "Improved transparency", "Increased stakeholder confidence"]),
        S("Enterprise Resource Planning (ERP) & Digital Transformation",
          "Prasad Consulting assists organisations in modernising operations through ERP adoption and digital transformation initiatives.",
          ["ERP readiness assessments", "Digital maturity evaluations", "Transformation planning", "Process digitalisation studies", "System integration guidance", "Technology adoption frameworks"],
          ["ERP Readiness Report", "Digital Transformation Roadmap", "Technology Adoption Plan", "Integration Framework"],
          ["Improved operational visibility", "Better information flow", "Increased automation", "Enhanced decision support"]),
        S("Executive Leadership Development & Management Training",
          "Prasad Consulting assists organisations in strengthening leadership capability and management effectiveness.",
          ["Executive development programmes", "Leadership workshops", "Strategic thinking programmes", "Management capability assessments", "Decision-making enhancement", "Professional development initiatives"],
          ["Leadership Development Framework", "Executive Training Programme", "Capability Assessment Report", "Leadership Roadmap"],
          ["Stronger leadership capability", "Improved management effectiveness", "Better organisational performance", "Enhanced succession readiness"]),
        S("Strategic Visioning & Organisational Alignment",
          "Prasad Consulting assists organisations in aligning people, processes and objectives with long-term strategic goals.",
          ["Vision workshops", "Alignment studies", "Strategic communication planning", "Goal cascading frameworks", "Organisational engagement initiatives", "Strategic alignment reviews"],
          ["Strategic Alignment Framework", "Vision Deployment Roadmap", "Organisational Alignment Report", "Leadership Recommendations"],
          ["Improved organisational focus", "Better strategic execution", "Enhanced employee engagement", "Stronger business outcomes"]),
        S("R&D Planning, Innovation Management & Technology Roadmapping",
          "Prasad Consulting assists organisations in building innovation capability and planning future technology initiatives.",
          ["Innovation assessments", "Technology roadmapping", "R&D planning", "Product innovation frameworks", "Emerging technology studies", "Innovation governance support"],
          ["Innovation Strategy Report", "Technology Roadmap", "R&D Planning Framework", "Innovation Management Blueprint"],
          ["Improved innovation capability", "Better technology planning", "Enhanced competitiveness", "Sustainable growth"]),
        S("Organisational Capability Development",
          "Prasad Consulting assists organisations in strengthening organisational competencies, skills and institutional capability.",
          ["Capability assessments", "Skills gap analysis", "Competency framework development", "Organisational development planning", "Workforce capability enhancement", "Institutional strengthening programmes"],
          ["Capability Assessment Report", "Competency Framework", "Organisational Development Plan", "Capability Enhancement Roadmap"],
          ["Stronger workforce capability", "Improved institutional effectiveness", "Better performance outcomes", "Increased organisational resilience"]),
        S("AI-Enabled Enterprise Transformation",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to accelerate business transformation and organisational performance.",
          ["AI transformation assessments", "AI-enabled process optimisation", "Predictive business analytics", "Intelligent decision-support systems", "AI strategy development", "AI adoption planning"],
          ["AI Transformation Strategy", "AI Opportunity Assessment", "Predictive Analytics Framework", "AI Adoption Roadmap", "Intelligent Enterprise Blueprint"],
          ["Faster transformation", "Better decision-making", "Enhanced operational intelligence", "Improved productivity", "Future-ready enterprise capability"]),
        S("Future-Ready Organisation Development",
          "Prasad Consulting assists organisations in preparing for future challenges, technological disruptions and evolving market conditions.",
          ["Future-readiness assessments", "Scenario planning", "Strategic resilience studies", "Workforce transformation planning", "Digital readiness evaluations", "Long-term capability development"],
          ["Future Readiness Assessment", "Strategic Resilience Framework", "Transformation Roadmap", "Capability Development Plan"],
          ["Enhanced adaptability", "Improved resilience", "Better long-term preparedness", "Sustainable competitive advantage"])
      ]
    },
    {
      id: "service-08",
      num: "08",
      title: "Foreign OEM Representation & India Market Enablement",
      desc: [
        "Prasad Consulting provides comprehensive India-entry support, strategic representation services, market enablement solutions and business development assistance to foreign Original Equipment Manufacturers (OEMs), international technology companies, defence manufacturers, aerospace organisations and global industrial enterprises seeking sustainable access to Indian markets.",
        "The objective is to assist foreign organisations in establishing an effective Indian presence, building local partnerships, understanding regulatory requirements, identifying opportunities, developing business relationships and successfully executing growth strategies within India's industrial, defence, aerospace, homeland security and commercial sectors.",
        "Prasad Consulting acts as a strategic adviser, market facilitator, business representative and trusted India partner for selected international organisations."
      ],
      subs: [
        S("India Market Entry Strategy",
          "Prasad Consulting assists foreign organisations in understanding the Indian business environment and establishing effective market entry strategies.",
          ["Market opportunity assessment", "Customer identification", "Industry analysis", "Competitor mapping", "Strategic entry planning", "Growth roadmap development"],
          ["India Market Assessment Report", "Market Entry Strategy", "Opportunity Matrix", "Growth Roadmap"],
          ["Faster market understanding", "Reduced entry risks", "Better strategic positioning", "Improved business outcomes"]),
        S("Professional Business Centre Establishment",
          "Prasad Consulting assists foreign organisations in establishing a professional operating presence and business support framework in India.",
          ["India business presence planning", "Administrative support structures", "Business representation frameworks", "Customer engagement support", "Operational guidance", "Market support systems"],
          ["India Presence Framework", "Business Support Architecture", "Operating Model Recommendations", "Implementation Roadmap"],
          ["Faster India readiness", "Reduced setup complexity", "Better operational efficiency", "Improved market accessibility"]),
        S("India Representation Services",
          "Prasad Consulting acts as a strategic representative and professional interface between foreign organisations and Indian stakeholders.",
          ["Market representation", "Customer liaison", "Business coordination", "Strategic communication support", "Opportunity engagement", "Relationship development"],
          ["Representation Framework", "Stakeholder Engagement Plan", "Business Development Reports", "Opportunity Tracking Reports"],
          ["Stronger market presence", "Improved customer access", "Better relationship management", "Enhanced business visibility"]),
        S("Business Development & Opportunity Management",
          "Prasad Consulting supports foreign organisations in identifying, pursuing and managing strategic opportunities in India.",
          ["Opportunity identification", "Customer mapping", "Business development planning", "Strategic engagement", "Pipeline management", "Opportunity pursuit support"],
          ["Business Development Plan", "Opportunity Pipeline Report", "Customer Engagement Framework", "Pursuit Strategy"],
          ["Better opportunity conversion", "Improved market penetration", "Enhanced customer engagement", "Increased business growth"]),
        S("Partner Identification & Indian Industry Partner Development",
          "Prasad Consulting assists foreign organisations in identifying and developing suitable Indian industrial partners.",
          ["Partner identification", "Capability assessment", "Strategic alignment reviews", "Partner evaluation", "Collaboration structuring", "Long-term relationship planning"],
          ["Partner Assessment Report", "Industry Partner Matrix", "Collaboration Framework", "Strategic Recommendations"],
          ["Better partnerships", "Reduced collaboration risks", "Improved localisation capability", "Enhanced market access"]),
        S("Channel Development & VAR Programmes",
          "Prasad Consulting assists organisations in developing effective distribution, reseller and Value-Added Reseller (VAR) networks.",
          ["Channel strategy development", "VAR framework creation", "Reseller identification", "Partner onboarding support", "Market expansion planning", "Sales enablement support"],
          ["Channel Development Plan", "VAR Framework", "Partner Network Blueprint", "Growth Strategy Report"],
          ["Expanded market reach", "Improved sales capability", "Better customer coverage", "Faster business growth"]),
        S("Build-to-Print & Licensed Production Facilitation",
          "Prasad Consulting assists organisations in establishing local manufacturing arrangements through Build-to-Print and Licensed Production models.",
          ["Manufacturing partner identification", "Capability assessments", "Production readiness reviews", "Industrial planning support", "Localisation studies", "Strategic production frameworks"],
          ["Production Strategy Report", "Localisation Framework", "Manufacturing Readiness Assessment", "Licensed Production Roadmap"],
          ["Reduced localisation risks", "Improved manufacturing capability", "Better market acceptance", "Enhanced long-term sustainability"]),
        S("Defence & Aerospace Market Enablement",
          "Prasad Consulting assists foreign defence and aerospace organisations in understanding and engaging with Indian defence and aerospace ecosystems.",
          ["Defence opportunity mapping", "Aerospace sector analysis", "Procurement understanding", "Customer engagement support", "Industrial ecosystem assessments", "Strategic growth planning"],
          ["Defence Market Assessment", "Aerospace Opportunity Study", "Strategic Engagement Framework", "Growth Roadmap"],
          ["Better market understanding", "Improved engagement capability", "Enhanced opportunity visibility", "Stronger competitive positioning"]),
        S("Tender Support, RFI/RFP Response Advisory & Bid Facilitation",
          "Prasad Consulting assists organisations in responding effectively to procurement opportunities.",
          ["RFI reviews", "RFP analysis", "Compliance assessments", "Bid strategy development", "Documentation guidance", "Submission support"],
          ["Bid Strategy Report", "Compliance Matrix", "Proposal Assessment", "Submission Framework"],
          ["Improved proposal quality", "Better compliance", "Enhanced competitiveness", "Increased success probability"]),
        S("Demonstrations, Customer Engagement & Opportunity Pursuit",
          "Prasad Consulting supports organisations in conducting demonstrations, presentations and customer engagement activities.",
          ["Demonstration planning", "Customer interaction support", "Capability presentation", "Technical engagement", "Opportunity pursuit planning", "Stakeholder coordination"],
          ["Demonstration Plan", "Engagement Strategy", "Opportunity Pursuit Framework", "Executive Briefing Notes"],
          ["Better customer engagement", "Enhanced product visibility", "Improved opportunity conversion", "Stronger market credibility"]),
        S("Defence Offsets, Industrial Cooperation & Technology Transfer",
          "Prasad Consulting assists foreign organisations in planning and executing offset obligations and technology collaboration initiatives.",
          ["Offset planning", "Industrial cooperation frameworks", "Technology transfer studies", "Localisation planning", "Partner development", "Strategic programme support"],
          ["Offset Strategy Report", "Technology Transfer Framework", "Industrial Cooperation Blueprint", "Strategic Recommendations"],
          ["Improved compliance", "Better localisation outcomes", "Enhanced industrial participation", "Sustainable long-term partnerships"]),
        S("AI-Enabled Market Intelligence & Opportunity Analytics",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to improve market visibility, opportunity tracking and strategic decision-making.",
          ["AI-assisted market intelligence", "Opportunity analytics", "Competitive monitoring", "Predictive business analytics", "Strategic trend forecasting", "Customer intelligence studies"],
          ["AI Market Intelligence Report", "Opportunity Analytics Dashboard", "Predictive Growth Assessment", "Strategic Insights Framework"],
          ["Faster decision-making", "Better opportunity identification", "Improved market awareness", "Enhanced competitive advantage"]),
        S("Long-Term India Operations Support",
          "Prasad Consulting provides sustained support for foreign organisations pursuing long-term business operations within India.",
          ["Strategic advisory", "Business coordination", "Customer support facilitation", "Partner relationship management", "Growth strategy reviews", "Business continuity support"],
          ["Long-Term Support Framework", "Strategic Advisory Reports", "Business Review Reports", "Growth Recommendations"],
          ["Stable India operations", "Stronger market relationships", "Improved business continuity", "Sustainable long-term growth"])
      ]
    },
    {
      id: "service-09",
      num: "09",
      title: "Defence Offsets, Industrial Partnerships & Technology Transfer",
      desc: [
        "Prasad Consulting provides strategic advisory, facilitation and implementation support services relating to defence offsets, industrial cooperation programmes, technology transfer initiatives, indigenous capability development, manufacturing partnerships and strategic industrial collaborations.",
        "The objective is to assist domestic and international organisations in creating mutually beneficial industrial ecosystems that accelerate technology absorption, capability development, localisation, indigenous manufacturing and long-term strategic growth.",
        "The consulting support extends across defence, aerospace, homeland security, maritime systems, advanced engineering, industrial technologies and emerging technology sectors."
      ],
      subs: [
        S("Defence Offset Strategy & Planning",
          "Prasad Consulting assists organisations in understanding, planning and executing defence offset obligations and opportunities.",
          ["Offset policy interpretation", "Offset strategy formulation", "Opportunity identification", "Partner mapping", "Offset project structuring", "Long-term offset planning"],
          ["Defence Offset Strategy Report", "Opportunity Assessment Matrix", "Offset Execution Framework", "Strategic Recommendations"],
          ["Improved offset compliance", "Better strategic positioning", "Increased industrial participation", "Enhanced business opportunities"]),
        S("Offset Programme Development & Execution",
          "Prasad Consulting assists organisations in developing and implementing structured offset programmes.",
          ["Offset project identification", "Programme planning", "Industrial participation mapping", "Compliance tracking", "Programme monitoring", "Stakeholder coordination"],
          ["Offset Programme Blueprint", "Implementation Roadmap", "Compliance Framework", "Progress Monitoring Structure"],
          ["Better programme execution", "Reduced compliance risks", "Improved stakeholder coordination", "Sustainable outcomes"]),
        S("Industrial Partnerships & Strategic Alliances",
          "Prasad Consulting facilitates strategic industrial collaborations between domestic and international organisations.",
          ["Partnership identification", "Capability matching", "Strategic alignment reviews", "Collaboration structuring", "Industrial cooperation planning", "Governance framework development"],
          ["Partnership Blueprint", "Alliance Framework", "Collaboration Strategy", "Strategic Recommendations"],
          ["Stronger partnerships", "Expanded industrial capabilities", "Improved market access", "Enhanced business growth"]),
        S("Transfer of Technology (ToT) Programmes",
          "Prasad Consulting assists organisations in planning, evaluating and implementing technology transfer initiatives.",
          ["ToT readiness assessments", "Technology absorption planning", "Capability development frameworks", "Technology transition planning", "Industrialisation support", "Technology integration strategies"],
          ["Technology Transfer Framework", "Technology Absorption Roadmap", "Capability Development Plan", "ToT Assessment Report"],
          ["Improved technology absorption", "Enhanced indigenous capability", "Faster industrialisation", "Sustainable technology growth"]),
        S("Intellectual Property (IP) Transfer & Commercialisation",
          "Prasad Consulting assists organisations in managing intellectual property transfer and commercialisation initiatives.",
          ["IP evaluation", "Commercialisation planning", "Licensing frameworks", "Strategic utilisation studies", "Partnership planning", "Value realisation assessments"],
          ["IP Transfer Strategy", "Commercialisation Framework", "Licensing Recommendations", "Strategic Assessment Report"],
          ["Improved value realisation", "Better technology utilisation", "Enhanced commercial outcomes", "Reduced strategic risks"]),
        S("Manufacturing Know-How Transfer",
          "Prasad Consulting assists organisations in transferring industrial knowledge, production expertise and manufacturing methodologies.",
          ["Manufacturing readiness assessments", "Production process transfer planning", "Capability development", "Workforce preparedness reviews", "Production optimisation", "Industrial support planning"],
          ["Manufacturing Transfer Plan", "Capability Development Framework", "Production Readiness Report", "Industrialisation Roadmap"],
          ["Faster capability creation", "Improved production readiness", "Enhanced industrial efficiency", "Sustainable growth"]),
        S("Build-to-Print Programme Facilitation",
          "Prasad Consulting supports organisations pursuing Build-to-Print manufacturing models.",
          ["Manufacturing partner identification", "Production capability assessments", "Process planning", "Industrial readiness reviews", "Localisation support", "Production ecosystem planning"],
          ["Build-to-Print Framework", "Manufacturing Assessment", "Production Readiness Study", "Strategic Recommendations"],
          ["Improved manufacturing capability", "Better localisation", "Reduced implementation risks", "Enhanced industrial participation"]),
        S("Licensed Production Programme Development",
          "Prasad Consulting assists organisations in establishing licensed production arrangements and associated industrial ecosystems.",
          ["Licensing assessments", "Industrial capability reviews", "Production planning", "Technology integration studies", "Industrial cooperation support", "Manufacturing strategy development"],
          ["Licensed Production Roadmap", "Capability Assessment Report", "Industrial Strategy Framework", "Production Planning Study"],
          ["Improved local manufacturing", "Better technology absorption", "Enhanced industrial participation", "Sustainable production capability"]),
        S("Indigenous Capability Development & Localisation",
          "Prasad Consulting supports organisations in building indigenous industrial capabilities and localisation frameworks.",
          ["Capability gap assessments", "Localisation planning", "Vendor development", "Technology adoption strategies", "Industrial ecosystem strengthening", "Strategic capability development"],
          ["Localisation Roadmap", "Capability Development Framework", "Industrial Readiness Assessment", "Strategic Recommendations"],
          ["Reduced import dependence", "Enhanced self-reliance", "Improved industrial strength", "Better competitiveness"]),
        S("Industrial Ecosystem Creation & Vendor Development",
          "Prasad Consulting assists organisations in developing strong industrial ecosystems and sustainable vendor networks.",
          ["Vendor identification", "Capability mapping", "Supplier assessments", "Ecosystem development", "Partnership frameworks", "Supply chain strengthening"],
          ["Vendor Development Plan", "Industrial Ecosystem Framework", "Capability Matrix", "Strategic Growth Roadmap"],
          ["Stronger supply chains", "Better industrial resilience", "Improved capability availability", "Sustainable growth"]),
        S("Joint Development & Co-Development Programmes",
          "Prasad Consulting supports collaborative technology development and joint product development initiatives.",
          ["Collaboration planning", "Capability integration", "Programme structuring", "Technology sharing frameworks", "Development roadmapping", "Partnership governance"],
          ["Co-Development Framework", "Programme Roadmap", "Strategic Collaboration Blueprint", "Governance Structure"],
          ["Shared development risks", "Faster innovation", "Improved resource utilisation", "Enhanced technology capability"]),
        S("Defence Industrial Corridor & Cluster Development Support",
          "Prasad Consulting assists governments, industrial agencies and organisations in developing defence industrial clusters and innovation ecosystems.",
          ["Cluster planning", "Capability mapping", "Industrial ecosystem studies", "Strategic infrastructure assessments", "Growth planning", "Policy-support recommendations"],
          ["Cluster Development Blueprint", "Industrial Ecosystem Assessment", "Strategic Growth Framework", "Infrastructure Planning Recommendations"],
          ["Enhanced industrial growth", "Better ecosystem integration", "Improved investment attraction", "Sustainable regional development"]),
        S("Maritime, Shipbuilding & Naval Industrial Partnerships",
          "Prasad Consulting assists organisations in creating strategic partnerships for maritime, naval and shipbuilding programmes.",
          ["Shipyard partnership planning", "Naval industrial cooperation", "Maritime manufacturing ecosystems", "Shipbuilding capability assessments", "Strategic infrastructure partnerships", "Naval technology collaboration"],
          ["Maritime Partnership Framework", "Shipbuilding Collaboration Blueprint", "Naval Industrial Ecosystem Study", "Strategic Development Roadmap"],
          ["Stronger maritime capabilities", "Improved industrial participation", "Enhanced shipbuilding readiness", "Sustainable maritime growth"]),
        S("AI-Enabled Industrial Collaboration & Technology Management",
          "Prasad Consulting assists organisations in leveraging Artificial Intelligence to optimise industrial collaboration, technology management and industrial growth.",
          ["AI-assisted partner matching", "AI-enabled technology assessments", "Predictive industrial analytics", "Technology portfolio management", "AI-driven localisation studies", "Intelligent collaboration frameworks"],
          ["AI Collaboration Assessment", "Technology Intelligence Framework", "Industrial Analytics Dashboard", "AI Transformation Roadmap"],
          ["Better collaboration decisions", "Improved technology visibility", "Enhanced strategic planning", "Faster industrial growth", "Future-ready industrial ecosystems"])
      ]
    },
    {
      id: "service-10",
      num: "10",
      title: "Academia\u2013Industry Collaboration & Innovation Ecosystems",
      desc: [
        "Prasad Consulting provides strategic advisory, institutional development support, outreach programmes, innovation ecosystem development, research facilitation and academia-industry collaboration services aimed at bridging the gap between education, research, technology and industry.",
        "The objective is to assist academic institutions, universities, engineering colleges, management institutions, research organisations, innovation centres, incubators, startups and industries in creating meaningful collaborations that improve employability, innovation, research capability, technology development and institutional excellence.",
        "This consulting domain promotes the creation of future-ready educational ecosystems capable of supporting contemporary industry needs, national technology objectives and innovation-driven growth."
      ],
      subs: [
        S("Academia-Industry Interface Development",
          "Prasad Consulting assists institutions and industries in creating structured collaboration frameworks that enable meaningful engagement and long-term value creation.",
          ["Industry engagement frameworks", "Academic collaboration models", "Corporate partnership development", "Knowledge exchange programmes", "Industry participation initiatives", "Collaborative ecosystem planning"],
          ["Academia-Industry Collaboration Framework", "Partnership Development Blueprint", "Engagement Roadmap", "Strategic Recommendations"],
          ["Improved industry connect", "Better employability outcomes", "Enhanced institutional relevance", "Stronger ecosystem development"]),
        S("Outreach Programmes, Masterclasses & Professional Workshops",
          "Prasad Consulting designs and conducts specialised knowledge-sharing programmes for students, faculty and industry professionals.",
          ["Masterclasses", "Technical seminars", "Strategic workshops", "Leadership programmes", "Industry awareness sessions", "Professional development initiatives"],
          ["Programme Design Framework", "Workshop Series", "Training Material", "Knowledge Enhancement Reports"],
          ["Enhanced professional awareness", "Improved learning outcomes", "Better industry exposure", "Stronger skill development"]),
        S("Curriculum Development & Academic Modernisation",
          "Prasad Consulting assists institutions in updating curricula to align with emerging technologies, industry requirements and future skill demands.",
          ["Curriculum reviews", "Syllabus redesign", "Elective development", "Industry integration studies", "Emerging technology incorporation", "Academic framework modernisation"],
          ["Curriculum Modernisation Report", "Syllabus Revision Framework", "Elective Design Recommendations", "Academic Transformation Roadmap"],
          ["Contemporary curriculum", "Improved student preparedness", "Better industry relevance", "Enhanced academic competitiveness"]),
        S("Industry-Oriented Training & Employability Enhancement",
          "Prasad Consulting assists institutions in improving graduate employability and professional readiness.",
          ["Employability assessments", "Industry readiness programmes", "Professional skills development", "Career enhancement initiatives", "Corporate orientation modules", "Industry exposure programmes"],
          ["Employability Enhancement Framework", "Industry Readiness Programme", "Career Development Roadmap", "Skills Assessment Reports"],
          ["Improved placement outcomes", "Better career readiness", "Enhanced student confidence", "Stronger industry acceptance"]),
        S("Research, Innovation & Product Development Support",
          "Prasad Consulting assists institutions and innovation teams in transforming ideas into products, technologies and commercially relevant outcomes.",
          ["Research project support", "Innovation mentoring", "Product development guidance", "Technology assessments", "Innovation frameworks", "Commercialisation pathways"],
          ["Innovation Strategy Report", "Research Roadmap", "Product Development Framework", "Commercialisation Guidance"],
          ["Improved research outcomes", "Enhanced innovation capability", "Better product development success", "Increased technology impact"]),
        S("Technology Incubation Centres & Innovation Ecosystems",
          "Prasad Consulting assists institutions in establishing incubation centres, innovation hubs, startup ecosystems and entrepreneurial platforms.",
          ["Incubation centre planning", "Innovation ecosystem design", "Startup support frameworks", "Entrepreneurial ecosystem development", "Innovation governance structures", "Industry engagement models"],
          ["Incubation Centre Blueprint", "Innovation Ecosystem Framework", "Startup Support Architecture", "Strategic Development Roadmap"],
          ["Strong innovation culture", "Increased startup creation", "Better industry participation", "Enhanced institutional visibility"]),
        S("Student Internship & Industry Exposure Programmes",
          "Prasad Consulting assists institutions in creating meaningful internship and industry immersion opportunities.",
          ["Internship programme design", "Industry partner engagement", "Exposure visit planning", "Project-oriented learning frameworks", "Professional mentoring", "Industry integration support"],
          ["Internship Framework", "Industry Engagement Plan", "Exposure Programme Structure", "Learning Outcome Matrix"],
          ["Better practical exposure", "Enhanced professional readiness", "Improved placement prospects", "Stronger industry interaction"]),
        S("Design Engineering, Systems Engineering & Product Realisation Training",
          "Prasad Consulting conducts specialised programmes aimed at developing engineering design, systems thinking and product development competencies.",
          ["Design engineering programmes", "Systems engineering workshops", "Product development mentoring", "Engineering methodology training", "Project guidance", "Innovation-oriented learning"],
          ["Training Framework", "Design Engineering Modules", "Systems Engineering Roadmap", "Capability Development Reports"],
          ["Enhanced engineering capability", "Improved design skills", "Better product development competence", "Stronger innovation outcomes"]),
        S("Laboratory Modernisation & Centre of Excellence Development",
          "Prasad Consulting assists institutions in establishing state-of-the-art laboratories, Centres of Excellence and specialised learning facilities.",
          ["Laboratory assessments", "CoE planning", "Infrastructure recommendations", "Equipment planning", "Industry-linked laboratory development", "Future laboratory architecture"],
          ["Laboratory Modernisation Blueprint", "Centre of Excellence Framework", "Infrastructure Development Plan", "Equipment Recommendations"],
          ["Improved learning infrastructure", "Better research capability", "Enhanced industry relevance", "Stronger institutional reputation"]),
        S("Industry Standards, Certifications & Accreditation Support",
          "Prasad Consulting assists institutions in understanding and implementing industry standards and accreditation frameworks.",
          ["Accreditation readiness assessments", "Standards familiarisation programmes", "Certification support", "Compliance guidance", "Institutional benchmarking", "Quality improvement initiatives"],
          ["Accreditation Readiness Report", "Standards Compliance Framework", "Certification Roadmap", "Quality Enhancement Plan"],
          ["Improved accreditation readiness", "Better quality outcomes", "Enhanced institutional credibility", "Increased stakeholder confidence"]),
        S("Institutional Excellence, Ranking & Global Recognition Support",
          "Prasad Consulting assists institutions in improving performance indicators, rankings and global visibility.",
          ["Ranking improvement studies", "Institutional benchmarking", "Strategic performance assessments", "Excellence framework development", "Reputation enhancement initiatives", "International positioning support"],
          ["Ranking Improvement Roadmap", "Excellence Assessment Report", "Strategic Development Framework", "Global Positioning Recommendations"],
          ["Improved rankings", "Enhanced visibility", "Better stakeholder perception", "Stronger institutional standing"]),
        S("Defence, Aerospace & Strategic Technology Academic Programmes",
          "Prasad Consulting assists institutions in creating specialised programmes focused on defence technologies, aerospace systems and strategic sectors.",
          ["Defence technology programmes", "Aerospace awareness initiatives", "Strategic technology workshops", "Industry-academia collaboration", "National technology mission support", "Specialised academic pathways"],
          ["Academic Programme Framework", "Technology Awareness Modules", "Strategic Technology Roadmap", "Industry Partnership Recommendations"],
          ["Enhanced strategic sector exposure", "Improved student opportunities", "Better industry linkage", "Increased national relevance"]),
        S("AI-Enabled Academic Transformation & Smart Learning Ecosystems",
          "Prasad Consulting assists institutions in integrating Artificial Intelligence into teaching, learning, administration and innovation ecosystems.",
          ["AI-enabled learning frameworks", "Smart campus strategies", "AI-assisted curriculum development", "Academic analytics", "Intelligent learning systems", "AI innovation programmes"],
          ["AI Academic Transformation Roadmap", "Smart Campus Framework", "AI Learning Ecosystem Blueprint", "Academic Analytics Strategy"],
          ["Improved learning outcomes", "Better institutional efficiency", "Enhanced innovation capability", "Future-ready educational ecosystems"]),
        S("Future Universities, Innovation Campuses & Knowledge Ecosystems",
          "Prasad Consulting assists institutions, governments and educational groups in conceptualising next-generation academic ecosystems.",
          ["Future university planning", "Innovation campus design", "Knowledge ecosystem development", "Strategic growth planning", "Multi-disciplinary integration studies", "Global education benchmarking"],
          ["Future University Blueprint", "Innovation Campus Master Plan", "Knowledge Ecosystem Framework", "Strategic Growth Roadmap"],
          ["Long-term institutional sustainability", "Enhanced innovation capacity", "Improved competitiveness", "Global academic relevance"])
      ]
    }
  ];
})();
